### ISSUE TITLE
mask and judgements files ?

### ISSUE THREAD

**Issue by lulu1315** [seanbell/intrinsic#1]
hello.just a question :
do I need these files ? and where can I get them (masks,judgements)
 -m <file>, --mask <file>
                        Mask filename
  -j <file>, --judgements <file>
                        Judgements file from the Intrinsic Images in the Wild
                        dataset
or do I just have to leave it like this as default.
thanks in advance
luc

**Comment by seanbell** [comment]
Both are optional.  The mask is if you have a dataset that uses masks (e.g. the MIT Intrinsic Images dataset).

The judgements file is optional -- if you specify it, it will measure the WHDR error for that image.  See the paper for an explanation of the judgemetns.

**Comment by lulu1315** [comment]
thank you.it's clear to me
